# Output formatter for TestMind AI
# Converts generated test cases to Markdown, JSON, CSV

import json
import csv
import io
from datetime import datetime


def to_markdown(test_cases: list[dict], feature: str = "") -> str:
    """
    Format test cases as a clean Markdown table with full details.
    Suitable for pasting into Confluence, Notion, or GitHub wikis.
    """
    lines = []

    if feature:
        lines.append(f"# Test Cases — {feature}")
        lines.append(f"*Generated by TestMind AI on "
                     f"{datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        lines.append("")

    lines.append(f"**Total:** {len(test_cases)} test cases")
    lines.append("")

    for tc in test_cases:
        lines.append(f"---")
        lines.append(f"### {tc.get('id','—')} — {tc.get('title','Untitled')}")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Type | {tc.get('type','—')} |")
        lines.append(f"| Priority | {tc.get('priority','—')} |")
        lines.append(f"| Preconditions | {tc.get('preconditions','None')} |")
        lines.append(f"| Test Data | {tc.get('test_data','N/A')} |")
        lines.append("")
        lines.append("**Steps:**")
        for i, step in enumerate(tc.get('steps', []), 1):
            lines.append(f"{i}. {step}")
        lines.append("")
        lines.append(f"**Expected Result:** {tc.get('expected_result','—')}")
        lines.append("")

    return "\n".join(lines)


def to_json(test_cases: list[dict], indent: int = 2) -> str:
    """Format test cases as formatted JSON string."""
    return json.dumps(test_cases, indent=indent, ensure_ascii=False)


def to_csv(test_cases: list[dict]) -> str:
    """
    Format test cases as CSV string.
    Steps are joined with ' | ' for single-cell representation.
    """
    if not test_cases:
        return ""

    fieldnames = ["id","title","type","priority","preconditions",
                  "steps","expected_result","test_data"]

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction='ignore')
    writer.writeheader()

    for tc in test_cases:
        row = dict(tc)
        if isinstance(row.get('steps'), list):
            row['steps'] = ' | '.join(row['steps'])
        writer.writerow(row)

    return output.getvalue()


def to_summary_table(test_cases: list[dict]) -> str:
    """
    Generate a compact summary table — good for quick overview.
    """
    lines = []
    lines.append(f"| # | ID | Title | Type | Priority |")
    lines.append(f"|---|----|----|------|----------|")

    for i, tc in enumerate(test_cases, 1):
        lines.append(
            f"| {i} | {tc.get('id','—')} | {tc.get('title','—')} "
            f"| {tc.get('type','—')} | {tc.get('priority','—')} |"
        )

    return "\n".join(lines)


def count_by_type(test_cases: list[dict]) -> dict:
    """Return frequency count of each test case type."""
    counts = {}
    for tc in test_cases:
        t = tc.get('type', 'Unknown')
        counts[t] = counts.get(t, 0) + 1
    return counts


def count_by_priority(test_cases: list[dict]) -> dict:
    """Return frequency count of each priority level."""
    counts = {}
    for tc in test_cases:
        p = tc.get('priority', 'Unknown')
        counts[p] = counts.get(p, 0) + 1
    return counts
